### ISSUE TITLE
GLFW: Invalid standard cursor OSX

### ISSUE THREAD

**Issue by hydroflame** [EngoEngine/engo#341]
$ go run pong.go 
panic: InvalidEnum: Cocoa: Invalid standard cursor

goroutine 1 [running, locked to thread]:
panic(0x42f3ae0, 0xc8200103e0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/go-gl/glfw/v3.1/glfw.acceptError(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/hydroflame/gopath/src/github.com/go-gl/glfw/v3.1/glfw/error.go:173 +0x136
github.com/go-gl/glfw/v3.1/glfw.panicError()
	/Users/hydroflame/gopath/src/github.com/go-gl/glfw/v3.1/glfw/error.go:184 +0x28
github.com/go-gl/glfw/v3.1/glfw.CreateStandardCursor(0x36001, 0x0)
	/Users/hydroflame/gopath/src/github.com/go-gl/glfw/v3.1/glfw/input.go:407 +0x31
engo.io/engo.CreateWindow(0x434f3c0, 0x9, 0x320, 0x320, 0xc820012600, 0x1)
	/Users/hydroflame/gopath/src/engo.io/engo/engo_glfw.go:48 +0xa8
engo.io/engo.Run(0x0, 0x434f3c0, 0x9, 0x0, 0x320, 0x320, 0x100, 0x3c, 0x0, 0x1, ...)
	/Users/hydroflame/gopath/src/engo.io/engo/engo.go:142 +0xb6e
main.main()
	/Users/hydroflame/gopath/src/engo.io/engo/demos/pong/pong.go:470 +0xcd
exit status 2

El capitain 10.11.5
go version go1.6 darwin/amd64

**Comment by hydroflame** [comment]
myb glfw not updated
