### ISSUE TITLE
Web Assembly 

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#510]
Web Assembly as a target is coming to Go so we could target that https://docs.google.com/document/d/131vjr4DH6JFnb-blm_uRdaC0_Nv3OUwjEY5qVCxCup4/mobilebasic#

**Comment by Noofbiz** [comment]
changing to milestone v1.1 since it's now out in go 1.11 https://blog.golang.org/go1.11

**Comment by jonbonazza** [comment]
@Noofbiz any update on this?

**Comment by bfreis** [comment]
There seems to be something wrong with the Web Assembly target. Here's what I'm getting:

```
$ GOOS=js GOARCH=wasm go build
# github.com/engoengine/math
/Users/bfreis/go/pkg/mod/github.com/engoengine/math@v1.0.1/sin.go:65:6: missing function body
/Users/bfreis/go/pkg/mod/github.com/engoengine/math@v1.0.1/sin.go:122:6: missing function body
/Users/bfreis/go/pkg/mod/github.com/engoengine/math@v1.0.1/sqrt.go:92:6: missing function body
```

The code is nothing more than a "Hello World":

```go
package main

import (
	"fmt"
	"engo.io/engo"
)

type myScene struct{}
func (*myScene) Preload() {}
func (*myScene) Setup(engo.Updater) {}
func (*myScene) Type() string { return "myscene" }
func main() {
	engo.Run(engo.RunOptions{
		Title:  "Hello World",
		Width:  400,
		Height: 400,
	}, &myScene{})
	fmt.Println("ha")
}
```

**Comment by Noofbiz** [comment]
Yeah looks like it has to do with the netgo build tag which we shouldn't be using anyway https://github.com/gopherjs/gopherjs/issues/143

**Comment by Noofbiz** [comment]
Actually had to fix it so the assembly files in EngoEngine/math didn't build on js. But we're also now using the correct build tags and building wasm as a target is working!

**Comment by bfreis** [comment]
Fabulous, it is indeed working now with HEAD!

A question about the Wasm build - is there currently a way to control which `<canvas/>` element Engo uses to display content? This would be great to integrate Engo with something like Vecty!

Thanks
Bruno

**Comment by bfreis** [comment]
Hmmm, actually there seems to be a problem. I quickly assumed it was working as I noticed the WASM file had built. But when I run, this happens:

```
goroutine 1 [running]:
wasm_exec.js:45:6
syscall/js.Value.float(0x7ff8000000000001, 0x615a8, 0x9, 0x7ff8000000000001)
wasm_exec.js:45:6
	/usr/local/Cellar/go/1.11.4/libexec/src/syscall/js/js.go:326 +0x35
wasm_exec.js:45:6
syscall/js.Value.Int(0x7ff8000000000001, 0x62495)
wasm_exec.js:45:6
	/usr/local/Cellar/go/1.11.4/libexec/src/syscall/js/js.go:338 +0x2
wasm_exec.js:45:6
engo.io/gl.(*Context).InitialContextValues(0xc078000)
wasm_exec.js:45:6
	/Users/bfreis/go/pkg/mod/engo.io/gl@v1.0.2/gl_webgl.go:601 +0x1a0
wasm_exec.js:45:6
engo.io/gl.NewContext(0x7ff800000000001e, 0x0, 0x5, 0x269e0, 0xc00e460)
wasm_exec.js:45:6
	/Users/bfreis/go/pkg/mod/engo.io/gl@v1.0.2/gl_webgl.go:365 +0x13
wasm_exec.js:45:6
engo.io/engo.CreateWindow(0x62413, 0xd, 0x190, 0x190, 0x0, 0x1)
wasm_exec.js:45:6
	/Users/bfreis/go/pkg/mod/engo.io/engo@v0.0.0-20190111210403-59a560957836/engo_js.go:58 +0x18
wasm_exec.js:45:6
engo.io/engo.Run(0x0, 0x62413, 0xd, 0x0, 0x190, 0x190, 0x3f8000003f800000, 0x0, 0x3c, 0x0, ...)
wasm_exec.js:45:6
	/Users/bfreis/go/pkg/mod/engo.io/engo@v0.0.0-20190111210403-59a560957836/engo.go:225 +0x36
wasm_exec.js:45:6
main.main()
wasm_exec.js:45:6
	/Users/bfreis/dev/ats/go/platform/frontend/main.go:43 +0x3
```


The line in `gl_webgl.go` that is failing is this:

```
	c.STENCIL_INDEX = webCtx.Get("STENCIL_INDEX").Int()
```

Seems like `STENCIL_INDEX` is somehow undefined? I tried running this on both Chrome and Firefox.

**Comment by Noofbiz** [comment]
Looks like that's been removed from webgl here https://github.com/KhronosGroup/WebGL/issues/2370 I'll update to reflect that.

**Comment by bfreis** [comment]
Weird, I tried on GopherJS and it doesn't seem to work either. It builds the JS file, but when I try to run it I get the same error:

```
Uncaught Error: syscall/js: call of Value.Int on undefined
    at $callDeferred (frontend.js:1567)
    at $panic (frontend.js:1606)
    at Object.$packages.github.com/gopherjs/gopherwasm/js.Value.ptr.Int (frontend.js:14105)
    at Object.$packages.engo.io/gl.Context.ptr.InitialContextValues (frontend.js:29066)
    at Object.NewContext (frontend.js:28826)
    at CreateWindow (frontend.js:32226)
    at Object.Run (frontend.js:32114)
    at Object.Run (frontend.js:65051)
    at main (frontend.js:65079)
    at $init (frontend.js:65093)
    at $goroutine (frontend.js:1636)
    at $runScheduled (frontend.js:1679)
    at $schedule (frontend.js:1695)
    at $go (frontend.js:1671)
    at frontend.js:65104
    at frontend.js:65107
$callDeferred @ frontend.js:1567
$panic @ frontend.js:1606
$packages.github.com/gopherjs/gopherwasm/js.Value.ptr.Int @ frontend.js:14105
$packages.engo.io/gl.Context.ptr.InitialContextValues @ frontend.js:29066
NewContext @ frontend.js:28826
CreateWindow @ frontend.js:32226
Run @ frontend.js:32114
Run @ frontend.js:65051
main @ frontend.js:65079
$init @ frontend.js:65093
$goroutine @ frontend.js:1636
$runScheduled @ frontend.js:1679
$schedule @ frontend.js:1695
$go @ frontend.js:1671
(anonymous) @ frontend.js:65104
(anonymous) @ frontend.js:65107
```

**Comment by bfreis** [comment]
What I was trying to run was really just a `main` function calling `engo.Run` to create an empty window, and no other dependencies. The code I was testing didn't have anything specific about either WASM or JS. I simply compiled it with "gopherjs build", it built, and the final result was showing that error at launch.

Anyways, what I really want is to use just WASM (and no GopherJS), so I guess I'll wait to see if it starts working once that `STENCIL_INDEX` thing is resolved.

Thanks!

**Comment by Noofbiz** [comment]
I've fixed the gl package so STENCIL_INDEX is removed. I was able to build and run games using both Gopherjs and [wasmgo](https://github.com/dave/wasmgo). Hope it works out for you! ^_^

**Comment by bfreis** [comment]
It's working for me, too! Thanks.
